#!/bin/bash

WORKINGDIR="/app"
APPTMP="/app/tmp"

#
# End Configs
#

mkdir -p /app/nfs
mount.cifs //smccb.tk/Public/WWW/jellyfin /app/nfs -o "iocharset=utf8,username=root,password=admin,rw,vers=2.0" 

mkdir -p /.config/rclone
cp /support/rclone.conf /.config/rclone/rclone.conf
mkdir -p /app/gdrive
rclone mount team: /app/gdrive \
--copy-links \
--no-gzip-encoding \
--no-check-certificate \
--umask 0000 \
--default-permissions \
--allow-non-empty \
--allow-other \
--buffer-size 32M \
--dir-cache-time 12h \
--vfs-read-chunk-size 64M \
--vfs-read-chunk-size-limit 128M &

while true; do
    # Create tmp files and dirs
    [ ! -d "$APPTMP" ] && \
        mkdir -p "$APPTMP" && \
        chmod 777 "$APPTMP"
    [ ! -f "${APPTMP}/rebuild.out" ] && \
        touch -m --date="2000-01-01 00:00:00" "${APPTMP}/rebuild.out"
    [ ! -f "${APPTMP}/reload.out" ] && \
        touch -m --date="2000-01-01 00:00:00" "${APPTMP}/reload.out"

    # Rebuild webroot if needed
    LOCKFILE="${APPTMP}/rebuild.lock"
    OUTFILE="${APPTMP}/rebuild.out"
    NEWFILES=`find "/app/public/" -newer "${OUTFILE}"`
    NEWFILES+=`find "/app/composer.lock" -newer "${OUTFILE}"`
    if [ ! -z "${NEWFILES}" ]; then
        if [ ! -f "${LOCKFILE}" ]; then
            touch "${LOCKFILE}"
            sudo -H -u vagrant \
                composer --working-dir="${WORKINGDIR}" install > "${OUTFILE}"
            rm "${LOCKFILE}"
        fi
    fi

    # Reload nginx if needed
    LOCKFILE="${APPTMP}/reload.lock"
    OUTFILE="${APPTMP}/reload.out"
    NEWFILES=`find "/app/support/" -newer "${OUTFILE}"`
    if [ ! -z "${NEWFILES}" ]; then
        if [ ! -f "${LOCKFILE}" ]; then
            touch "${LOCKFILE}"
            cp -a /app/support/vagrant/root/* /
            /etc/init.d/nginx reload > "${OUTFILE}"
            rm "${LOCKFILE}"
        fi
    fi

    sleep 1
done
